# Table 2: Standard APO on GPT-3.5-turbo, Biosses task.
# Paper Section 4.1. tau_warmup = 4 for this task.

task_name: biosses
search_algo: tras
print_log: true
log_dir: ./logs/

init_prompt: |
  Decide if these two sentences are (A) Not similar (B) Somewhat similar (C) Similar.

task_setting:
  train_size: 40
  eval_size: 20
  test_size: 40
  seed: 1909
  data_dir: biosses.py
  post_instruction: false

base_model_setting:
  model_type: openai
  model_name: gpt-3.5-turbo
  temperature: 0.0
  max_tokens: 4096
  api_key: null
  device: null
  model_path: null
  max_parallel_requests: 5

optim_model_setting:
  model_type: openai
  model_name: gpt-4o
  temperature: 1.0
  max_tokens: 4096
  api_key: null
  device: null
  model_path: null
  max_parallel_requests: 5

search_setting:
  iteration_num: 15
  expand_width: 3
  depth_limit: 8
  min_depth: 2
  w_exp: 2.5
  beam_width: 3

world_model_setting:
  train_shuffle: true
  num_new_prompts: 1
  train_batch_size: 5
  eval_batch_size: 5
  test_batch_size: 5
  regularization_warmup_depth: 4
  mcsa_samples: 6
